/*
 * 공항 교통편 · 예약 정보
 *   AIRPORT_ACCESS : 공항 코드별 시내 교통편 (hubs = 내리는 주요 역과 공항에서 걸리는 분)
 *   RESERVATIONS   : 도시별로 예약이 필요하거나 하면 좋은 곳 (PLACES / KNOWN_SPOTS id)
 * 요금·시간 근거: 2025~2026 각 운영사 공식 사이트 검색 결과 (편도 성인, 대략). 요금 개정이 잦으니 참고용.
 */

// 공항 → 시내 교통편. 숙소 위치에 따라 엔진이 가장 빠른 것을 고른다 (공항→도착역 시간 + 도착역→숙소 이동).
const AIRPORT_ACCESS = {
  NRT: [
    { id: 'skyliner', name: '스카이라이너', kind: 'rail',
      hubs: [
        { name: '닛포리', lat: 35.7281, lng: 139.7707, min: 36 },
        { name: '게이세이우에노', lat: 35.7113, lng: 139.7745, min: 41 },
      ],
      price: 2580, reserve: 'recommended',
      url: 'https://www.keisei.co.jp/keisei/tetudou/skyliner/e-ticket/ko/',
      urlLabel: '스카이라이너 e-티켓 (한국어)',
      note: '우에노·아사쿠사·닛포리 쪽 숙소에 가장 빨라요. 온라인 할인 티켓이 있어요' },
    { id: 'nex', name: '나리타 익스프레스 (N\'EX)', kind: 'rail',
      hubs: [
        { name: '도쿄역', lat: 35.6812, lng: 139.7671, min: 55 },
        { name: '시나가와', lat: 35.6285, lng: 139.7388, min: 68 },
        { name: '시부야', lat: 35.6580, lng: 139.7016, min: 78 },
        { name: '신주쿠', lat: 35.6896, lng: 139.7006, min: 83 },
      ],
      price: 3070, reserve: 'recommended',
      url: 'https://www.jreast.co.jp/kr/pass/nex_round.html',
      urlLabel: 'N\'EX 도쿄 왕복 티켓 (한국어)',
      note: '전석 지정석. 외국인 전용 왕복권(5,200엔)이 편도 두 번보다 훨씬 싸요. 신주쿠·시부야·도쿄역 숙소에 환승 없이' },
    { id: 'keisei_access', name: '게이세이 액세스 특급 (아사쿠사선 직통)', kind: 'rail',
      hubs: [
        { name: '아사쿠사', lat: 35.7108, lng: 139.7967, min: 65 },
        { name: '니혼바시', lat: 35.6822, lng: 139.7745, min: 72 },
        { name: '히가시긴자', lat: 35.6693, lng: 139.7671, min: 76 },
      ],
      price: 1300, reserve: 'none',
      url: null, urlLabel: null,
      note: '지정석 없는 일반 열차라 싸요. 아사쿠사·긴자 쪽 숙소에 환승 없이' },
    { id: 'keisei_ltd', name: '게이세이 본선 특급 (가장 저렴)', kind: 'rail',
      hubs: [
        { name: '닛포리', lat: 35.7281, lng: 139.7707, min: 75 },
        { name: '게이세이우에노', lat: 35.7113, lng: 139.7745, min: 80 },
      ],
      price: 1050, reserve: 'none',
      url: null, urlLabel: null,
      note: '시간은 걸리지만 가장 싼 방법. 짐이 적을 때 추천' },
    { id: 'limo_nrt_shinjuku', name: '리무진 버스 (신주쿠행)', kind: 'bus',
      hubs: [ { name: '바스타 신주쿠', lat: 35.6883, lng: 139.7003, min: 105 } ],
      price: 3600, reserve: 'none',
      url: 'https://www.limousinebus.co.jp/ko/line/detail/Narita-Shinjuku/',
      urlLabel: '리무진 버스 나리타↔신주쿠 (한국어)',
      note: '짐이 많을 때 편해요. 신주쿠 주요 호텔 앞에도 서요. 퇴근 시간엔 정체 주의' },
    { id: 'tyo_nrt', name: '에어포트 버스 TYO-NRT (도쿄역행)', kind: 'bus',
      hubs: [ { name: '도쿄역 야에스구치', lat: 35.6804, lng: 139.7700, min: 65 } ],
      price: 1500, reserve: 'none',
      url: 'https://tyo-nrt.com/en', urlLabel: 'TYO-NRT 공식 (영어)',
      note: '도쿄역까지 가장 싼 직행. 밤 11시 이후는 3,000엔' },
  ],

  HND: [
    { id: 'keikyu', name: '게이큐선 (시나가와 · 아사쿠사선 직통)', kind: 'rail',
      hubs: [
        { name: '시나가와', lat: 35.6285, lng: 139.7388, min: 15 },
        { name: '히가시긴자', lat: 35.6693, lng: 139.7671, min: 30 },
        { name: '니혼바시', lat: 35.6822, lng: 139.7745, min: 33 },
        { name: '아사쿠사', lat: 35.7108, lng: 139.7967, min: 42 },
      ],
      price: 330, reserve: 'none',
      url: 'https://www.haneda-tokyo-access.com/kr/ride/fares.html',
      urlLabel: '게이큐 운임·소요시간 (한국어)',
      note: '시나가와에서 JR 야마노테선 환승. 아사쿠사행 직통 열차면 긴자·아사쿠사까지 환승 없이 (아사쿠사까지 약 600엔)' },
    { id: 'monorail', name: '도쿄 모노레일', kind: 'monorail',
      hubs: [ { name: '하마마쓰초', lat: 35.6555, lng: 139.7571, min: 15 } ],
      price: 520, reserve: 'none',
      url: 'https://www.tokyo-monorail.co.jp/english/haneda-tokyo-access/',
      urlLabel: '도쿄 모노레일 공식 (영어)',
      note: '하마마쓰초에서 JR 야마노테선 환승. 도쿄타워·시바 쪽 숙소에 가까워요' },
    { id: 'limo_hnd_shinjuku', name: '리무진 버스 (신주쿠행)', kind: 'bus',
      hubs: [ { name: '바스타 신주쿠', lat: 35.6883, lng: 139.7003, min: 50 } ],
      price: 1400, reserve: 'none',
      url: 'https://www.limousinebus.co.jp/ko/timetable/',
      urlLabel: '리무진 버스 시간표·예약 (한국어)',
      note: '환승 없이 신주쿠까지. 짐 많은 가족·부모님 동반에 편해요' },
  ],

  KIX: [
    { id: 'haruka', name: 'JR 특급 하루카', kind: 'rail',
      hubs: [
        { name: '덴노지', lat: 34.6465, lng: 135.5133, min: 33 },
        { name: '신오사카', lat: 34.7334, lng: 135.5001, min: 50 },
        { name: '교토', lat: 34.9858, lng: 135.7588, min: 75 },
      ],
      price: 1800, reserve: 'recommended',
      url: 'https://www.westjr.co.jp/travel-information/kr/tickets-passes/oneway/haruka/',
      urlLabel: 'HARUKA 편도 티켓 (JR서일본 한국어)',
      note: '외국인 전용 할인 편도권을 미리 사면 싸요 (덴노지는 더 저렴, 교토는 조금 비쌈). ICOCA 교통카드와 함께 사두면 편해요' },
    { id: 'rapit', name: '난카이 특급 라피트', kind: 'rail',
      hubs: [
        { name: '덴가차야', lat: 34.6368, lng: 135.4957, min: 31 },
        { name: '난바', lat: 34.6626, lng: 135.5016, min: 38 },
      ],
      price: 1670, reserve: 'recommended',
      url: 'https://www.nankai.co.jp/kr_railway/ticket/rapit',
      urlLabel: '라피트 디지털 티켓 (난카이 한국어)',
      note: '전석 지정석. 난바·도톤보리·신사이바시 숙소에 가장 빨라요' },
    { id: 'nankai_express', name: '난카이 공항급행', kind: 'rail',
      hubs: [
        { name: '덴가차야', lat: 34.6368, lng: 135.4957, min: 40 },
        { name: '난바', lat: 34.6626, lng: 135.5016, min: 45 },
      ],
      price: 970, reserve: 'none',
      url: 'https://www.nankai.co.jp/kr_railway/access-timetable',
      urlLabel: '난카이 시간표 (한국어)',
      note: '라피트보다 7분 정도 느리지만 훨씬 싸요. 교통카드로 바로 탑승' },
    { id: 'limo_kix', name: '공항 리무진 버스 (우메다 · 난바행)', kind: 'bus',
      hubs: [
        { name: '난바 (OCAT)', lat: 34.6680, lng: 135.4955, min: 50 },
        { name: '오사카역 (우메다)', lat: 34.7066, lng: 135.4972, min: 60 },
      ],
      price: 1800, reserve: 'none',
      url: 'https://www.kate.co.jp/kr/timetable/',
      urlLabel: '간사이공항 리무진 버스 시간표·운임 (한국어)',
      note: '짐이 많거나 우메다 쪽 숙소일 때 환승 없이. 선착순 탑승' },
  ],

  ITM: [
    { id: 'itm_monorail', name: '오사카 모노레일 + 한큐선', kind: 'monorail',
      hubs: [ { name: '오사카우메다 (한큐)', lat: 34.7053, lng: 135.4989, min: 29 } ],
      price: 440, reserve: 'none',
      url: 'https://www.osaka-monorail.co.jp/language/en/route/hotarugaike-route/',
      urlLabel: '오사카 모노레일 공식 (영어)',
      note: '모노레일로 호타루가이케(1정거장)까지 가서 한큐 다카라즈카선 환승' },
    { id: 'limo_itm', name: '공항 리무진 버스 (우메다 · 난바행)', kind: 'bus',
      hubs: [
        { name: '오사카역 (우메다)', lat: 34.7025, lng: 135.4959, min: 25 },
        { name: '난바 (OCAT)', lat: 34.6680, lng: 135.4955, min: 30 },
      ],
      price: 650, reserve: 'none',
      url: 'https://www.osaka-airport.co.jp/en/access/bus',
      urlLabel: '이타미공항 버스 안내 (영어)',
      note: '환승 없이 우메다·난바까지. 난바행은 730엔' },
  ],

  CTS: [
    { id: 'jr_airport', name: 'JR 쾌속 에어포트', kind: 'rail',
      hubs: [
        { name: '삿포로역', lat: 43.0686, lng: 141.3508, min: 37 },
        { name: '오타루', lat: 43.1976, lng: 140.9939, min: 75 },
      ],
      price: 1150, reserve: 'none',
      url: 'https://www.jrhokkaido.co.jp/global/korean/index.html',
      urlLabel: 'JR홋카이도 공식 (한국어)',
      note: '약 10분 간격. 특별쾌속은 삿포로까지 33분. 오타루까지는 1,910엔' },
    { id: 'jr_useat', name: 'JR 쾌속 에어포트 u시트 (지정석)', kind: 'rail',
      hubs: [
        { name: '삿포로역', lat: 43.0686, lng: 141.3508, min: 37 },
        { name: '오타루', lat: 43.1976, lng: 140.9939, min: 75 },
      ],
      price: 2150, reserve: 'recommended',
      url: 'https://www.jrhokkaido.co.jp/global/korean/ticket/reservation/index.html',
      urlLabel: 'JR홋카이도 열차 예약 (한국어)',
      note: '4호차 지정석(+1,000엔). 스키 시즌·저녁 도착편은 자유석이 붐벼서 예약하면 앉아 갈 수 있어요' },
    { id: 'cts_bus', name: '공항 연락 버스 (삿포로 시내행)', kind: 'bus',
      hubs: [
        { name: '삿포로역', lat: 43.0673, lng: 141.3510, min: 65 },
        { name: '오도리', lat: 43.0598, lng: 141.3544, min: 73 },
        { name: '스스키노', lat: 43.0556, lng: 141.3530, min: 77 },
      ],
      price: 1500, reserve: 'none',
      url: 'https://www.hokto.co.jp/en/sapporo-chitose/',
      urlLabel: '호쿠토교통 공항버스 (영어)',
      note: '오도리·스스키노 호텔 근처에 바로 내려요. 겨울 눈길엔 지연 가능' },
  ],

  FUK: [
    { id: 'fuk_subway', name: '후쿠오카 지하철 공항선', kind: 'subway',
      hubs: [
        // 한국발 항공편은 국제선 도착이라 국내선 터미널까지 셔틀 약 15분을 더한 시간
        { name: '하카타', lat: 33.5902, lng: 130.4207, min: 20 },
        { name: '나카스카와바타', lat: 33.5946, lng: 130.4062, min: 24 },
        { name: '텐진', lat: 33.5911, lng: 130.3990, min: 26 },
      ],
      price: 260, reserve: 'none',
      url: 'https://subway.city.fukuoka.lg.jp/kor/',
      urlLabel: '후쿠오카시 지하철 (한국어)',
      note: '국내선 터미널 역에서 출발해요. 국제선 도착이면 무료 셔틀버스로 국내선까지 가야 해요 (시간에 포함)' },
    { id: 'fuk_intl_bus', name: '국제선 → 하카타·텐진 직행 버스 (니시테츠)', kind: 'bus',
      hubs: [
        { name: '하카타 버스터미널', lat: 33.5895, lng: 130.4196, min: 20 },
        { name: '니시테츠 텐진 고속버스터미널', lat: 33.5881, lng: 130.3993, min: 35 },
      ],
      price: 310, reserve: 'none',
      url: 'https://www.nishitetsu.jp/en/access/',
      urlLabel: '니시테츠 공항 액세스 (영어)',
      note: '국제선 터미널 앞에서 바로 타요. 텐진행 직행은 500엔' },
  ],
};

// 예약이 필요하거나 하면 좋은 곳 (도시별, PLACES id 또는 KNOWN_SPOTS id)
//   level: 'required' 예약 필수 · 'recommended' 예약하면 좋음 · 'queue' 예약 불가, 줄 서기
const RESERVATIONS = {
  tokyo: {
    shibuyasky: { level: 'required', why: '날짜·시간 지정 티켓. 일몰 시간대는 2주 전 판매 시작 직후 매진돼요',
      url: 'https://www.shibuya-scramble-square.com/sky/ticket/', urlLabel: '시부야 스카이 공식 티켓' },
    teamlab: { level: 'required', why: '30분 단위 입장 시간 예약제. 주말·연휴는 미리 매진',
      url: 'https://www.teamlab.art/e/planets/', urlLabel: '팀랩 플래닛 공식 (한국어 지원)' },
    disneyland: { level: 'required', why: '날짜 지정 티켓을 온라인으로 미리 사야 해요 (매진·변동 가격)',
      url: 'https://www.tokyodisneyresort.jp/kr/ticket/index.html', urlLabel: '도쿄 디즈니 리조트 파크 티켓 (한국어)' },
    disneysea: { level: 'required', why: '날짜 지정 티켓을 온라인으로 미리 사야 해요 (매진·변동 가격)',
      url: 'https://www.tokyodisneyresort.jp/kr/ticket/index.html', urlLabel: '도쿄 디즈니 리조트 파크 티켓 (한국어)' },
    skytree: { level: 'recommended', why: '온라인 날짜·시간 지정권이 당일권보다 싸고 대기 없이 입장 (30일 전부터)',
      url: 'https://www.tokyo-skytree.jp/kr/ticket/', urlLabel: '도쿄 스카이트리 티켓 (한국어)' },
    ginzasushi: { level: 'required', why: '카운터 좌석이 적어 오마카세는 대부분 예약제예요', url: null, urlLabel: null },
    motomura: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    ichiran_t: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    maisen: { level: 'queue', why: '점심 피크엔 대기가 길어요 · 오픈 직후 추천', url: null, urlLabel: null },
    k_ichinisan: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    k_tsujihan: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    k_fuunji: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    k_kagari: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    k_gyukaku_kabukicho: { level: 'recommended', why: '저녁 무한리필은 금·토에 만석이 많아요. 온라인 예약 가능', url: null, urlLabel: null },
    k_king_shinjuku: { level: 'recommended', why: '저녁 무한리필은 대기가 길어요. 예약하면 바로 입장', url: null, urlLabel: null },
    k_anan_dogenzaka: { level: 'recommended', why: '저녁 시간대 예약 추천', url: null, urlLabel: null },
  },
  osaka: {
    usj: { level: 'required', why: '날짜 지정 입장권 + 익스프레스 패스(인기 어트랙션·닌텐도 월드 입장 보장)는 미리 매진돼요',
      url: 'https://usj.co.jp/kr/index.html', urlLabel: '유니버설 스튜디오 재팬 공식 (한국어)' },
    kaiyukan: { level: 'recommended', why: '날짜 지정 e-티켓을 사면 매표소 줄 없이 입장 (30일 전부터)',
      url: 'https://pop.kaiyukan.com/language/korean/ticket.html', urlLabel: '가이유칸 티켓 (한국어)' },
    zouheikyoku: { level: 'required', why: '인터넷 사전 신청제 (2026년 기준, 선착순). 신청 없이는 입장 불가 (4월 중순 1주일)',
      url: 'https://www.mint.go.jp/', urlLabel: '조폐국 공식 (신청 안내)' },
    k_pokemon_osaka: { level: 'recommended', why: '포켓몬 센터는 자유 입장, 포켓몬 카페는 31일 전 18시 예약 오픈 후 금방 매진',
      url: 'https://www.pokemon-cafe.jp/ko/cafe/reservation.html', urlLabel: '포켓몬 카페 예약 (한국어)' },
    kani: { level: 'recommended', why: '저녁 코스는 예약하는 게 안전해요. 온라인 예약 가능',
      url: 'https://www.hotpepper.jp/strJ000018294/yoyaku/', urlLabel: '카니도라쿠 도톤보리 본점 예약 (핫페퍼)' },
    tsuruhashi: { level: 'recommended', why: '인기 야키니쿠집은 저녁에 예약 추천', url: null, urlLabel: null },
    kushikatsu: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    ichiran_o: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    mizuno: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    k_motomura_namba: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    k_harukoma: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    k_rikuro: { level: 'queue', why: '구워 나오는 시간마다 줄이 생겨요 · 오전 추천', url: null, urlLabel: null },
    k_ebisu_umeda: { level: 'recommended', why: '저녁 무한리필은 예약 추천', url: null, urlLabel: null },
    k_gyukaku_dotonbori: { level: 'recommended', why: '저녁 무한리필은 주말 만석이 많아요. 온라인 예약 가능', url: null, urlLabel: null },
    k_king_namba: { level: 'recommended', why: '저녁 무한리필은 대기가 길어요. 예약하면 바로 입장', url: null, urlLabel: null },
  },
  sapporo: {
    kanihonke: { level: 'recommended', why: '개별실 게 코스는 저녁에 예약하는 게 안전해요',
      url: 'https://www.kani-honke.co.jp/en/', urlLabel: '삿포로 카니혼케 공식' },
    k_kaniza: { level: 'recommended', why: '게 무한리필은 시간제라 예약 추천', url: null, urlLabel: null },
    k_beergarden: { level: 'recommended', why: '징기스칸 무한리필은 저녁·주말 예약 추천', url: null, urlLabel: null },
    beer: { level: 'recommended', why: '박물관은 무료 자유 관람, 시음 포함 프리미엄 투어는 사전 예약제',
      url: 'https://www.sapporobeer.jp/brewery/s_museum/', urlLabel: '삿포로 맥주 박물관 공식' },
    shiroikoibito: { level: 'recommended', why: '과자 만들기 체험은 사전 예약', url: 'https://www.shiroikoibitopark.jp/', urlLabel: '시로이 코이비토 파크 공식' },
    biei: { level: 'recommended', why: '차 없이 가면 삿포로 출발 버스 투어를 미리 예약해야 해요 (라벤더 시즌 매진)', url: null, urlLabel: null },
    jingisukan: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    garaku: { level: 'queue', why: '예약 불가, 번호표 · 오픈 직후 추천', url: null, urlLabel: null },
    suage: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    sumire: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    toriton: { level: 'queue', why: '예약 불가, 번호표 발권 · 오픈 직후 추천', url: null, urlLabel: null },
    hanamaru: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    k_ichigen: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    k_shingen: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    k_gyukaku_susukino: { level: 'recommended', why: '저녁 무한리필은 예약 추천. 온라인 예약 가능', url: null, urlLabel: null },
  },
  fukuoka: {
    motsunabe: { level: 'recommended', why: '저녁엔 예약 없이 가면 한참 기다려요', url: null, urlLabel: null },
    k_rakutenchi: { level: 'recommended', why: '저녁 예약 추천', url: null, urlLabel: null },
    k_hachibei: { level: 'recommended', why: '작은 가게라 저녁 예약 추천', url: null, urlLabel: null },
    k_gyukaku_nakasu: { level: 'recommended', why: '저녁 무한리필은 예약 추천. 온라인 예약 가능', url: null, urlLabel: null },
    k_gyukaku_tenjin: { level: 'recommended', why: '저녁 무한리필은 예약 추천. 온라인 예약 가능', url: null, urlLabel: null },
    ichiran_f: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    shinshin: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    hyotan: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    mentaiju: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    unagi: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    k_daruma: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    k_udontaira: { level: 'queue', why: '예약 불가, 줄 서기 · 오픈 직후 추천', url: null, urlLabel: null },
    k_kiwamiya: { level: 'queue', why: '예약 불가, 번호표 · 오픈 직후 추천', url: null, urlLabel: null },
  },
};
